[tool.ruff]
target-version = "py312"
line-length = 88
exclude = ["typings", ".venv"]

[tool.black]
line-length = 88
target-version = ["py312"]
exclude = "/(typings|.venv|node_modules)/"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "COM812"]
per-file-ignores = {"tests/*.py" = ["S101"]}

[tool.ruff.format]
# This section is required if you want to use Ruff as a formatter (not needed for lint-only)
# If you want Ruff to only error, not fix, just use the linter (as in your config)

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
asyncio_mode = "auto" # Fix deprecation warning
asyncio_default_fixture_loop_scope = "function" # Explicitly set scope for warning
testpaths = [
    "tests",
]
markers = [
    "e2e: marks tests as end-to-end tests requiring Docker"
]

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportMissingImports = true
reportMissingTypeStubs = false
include = ["app", "tests"]
exclude = ["node_modules", ".venv"]
venvPath = "."
venv = ".venv"

# File-specific overrides to silence persistent errors in conftest.py
[[tool.pyright.fileOptions]]
  file = "tests/conftest.py"
  reportUnknownVariableType = "none"
  reportUnknownArgumentType = "none"
  reportUnknownMemberType = "none"
  reportAttributeAccessIssue = "none"
